import './globals.css'
import NavBar from '@/components/NavBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const tittuloNav = 'Dimensiones';
  const linksNav = [
  
    { url: './overworld', text: 'Overworld ' },
    { url: './nether', text: 'Nether' },
    { url: './end', text: 'End' },

    
    
  ];
  return (
    <html lang="en">
      <body>
        <NavBar tittuloNav={tittuloNav} linksNav={linksNav}/>
        {children}
        </body>
    </html>
  )
}
