import React from 'react';
import NavBar from '@/components/NavBar';
import styles from '@/styles/end.module.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  const tittuloNav = 'Dimensiones';
  const linksNav = [
    { url: './overworld', text: 'Overworld ' },
    { url: './nether', text: 'Nether' },
    { url: './end', text: 'End' },
  ];

  return (
    <div className={styles.body}>
      <NavBar tittuloNav={tittuloNav} linksNav={linksNav} />
      {children}
    </div>
  );
}

export default RootLayout;  // Solo exporta RootLayout
